/** Common job titles for onboarding quick-add chips. */
export const ROLE_PRESETS = [
  "Manager",
  "Supervisor",
  "Shift Supervisor",
  "Team Lead",
  "Server",
  "Waiter",
  "Bartender",
  "Host",
  "Chef",
  "Cook",
  "Kitchen Hand",
  "Barista",
  "Cashier",
  "Retail Associate",
  "Sales Associate",
  "Merchandiser",
  "Warehouse Associate",
  "Picker / Packer",
  "Delivery Driver",
  "Dispatch",
  "Logistics Coordinator",
  "Pump Attendant",
  "Event Staff",
  "Cleaner",
  "Security",
  "Reception",
] as const;

/** Common org departments (optional secondary field). */
export const DEPARTMENT_PRESETS = [
  "Administration",
  "Front of House",
  "Kitchen",
  "Bar",
  "Sales",
  "Warehouse",
  "Accounting",
  "Human Resources",
  "Maintenance",
  "Security",
] as const;
